carRentals-MVC/CarRentalsApp-WEB/Controllers/CarController.cs
using CarRentalsApp_WEB.Application.Contracts.IServices;
using CarRentalsApp_WEB.Models.Enums;
using CarRentalsApp_WEB.Models.Models;
using CarRentalsApp_WEB.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace CarRentalsApp_WEB.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService _carService;

        public CarController(ICarService carService)
        {
            _carService = carService;
        }



        public async Task<IActionResult> Index(int pageSize= 9, int pageNumber = 1)
        {
            var paginatedCars = await _carService.GetAllCarsListing(pageSize, pageNumber);

           
            return View(paginatedCars.Data);
        }

        [Route("Details/{Id}")]
        public async Task<IActionResult> Details(string Id)

        {
            var carDetails = await _carService.GetAllCarDetails(Id);
            return View(carDetails.Data);
        }


        public async Task<IActionResult> Offers(int pageSize = 9, int pageNumber = 1)

        {
            var offerCars = await _carService.GetAllCarsOffers(pageSize, pageNumber);
            return View(offerCars.Data);
        }

        public IActionResult Summary(CarBookTripViewModel model)
        {
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Payment(PaymentRequestViewModel model)
        {
            var result = await _carService.CarPayment(model);
            if (result.IsSuccessful)
                return Redirect(result.Data.AuthorizationUrl);
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> SearchCar(CarSearchViewModel model)
        {
           

            var search = await _carService.CarSearch(model);
            return View(search.Data);
        }


        [HttpPost]
        public async Task<IActionResult> BookCarTrip(CarBookTripViewModel model)
        {
            var loggedinUser = HttpContext.Session.GetString("User");

            if(string.IsNullOrWhiteSpace(loggedinUser))
            {
                HttpContext.Session.SetString("ReturnUrl", Request.Headers["Referer"].ToString());
                ModelState.AddModelError(string.Empty, "You need to login before booking!!!");
                return RedirectToAction("Login", "Auth");
            }

            var user = JsonConvert.DeserializeObject<UserResponseViewModel>(loggedinUser);

            var trip = new TripRequestViewModel()
            {
                CarId = model.CarId,
                UserId = user.Id,
                Pickupdate = model.Pickupdate,
                Returndate = model.Returndate
            };

            var search = await _carService.CarBookTrip(trip);
            model.UserId = user.Id;
            model.TripId = search.Data.Id;
            if(search.IsSuccessful)
                return RedirectToAction("Summary", model);

            return View();
        }
    }
}

carRentals-MVC/CarRentalsApp-WEB/Views/Car/Details.cshtml
@model CarDetailsViewModel

@{
    ViewData["Title"] = "CAR DETAILS";

    
}

<br>
<br>
<br>
<p></p>

<div class="container mt-5 mb-5 pt-5">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-md-12">
                    <div class="thumbnail">
                         <img src="@Model.Images.Where(x => x.IsFeature == true).FirstOrDefault().ImageUrl" alt="Lights" style="width:100%; height:400px" class="img-responsive" />
                    </div>
                </div>
            </div>

            <div class="row">
                @foreach (var item in Model.Images)
                {
                    if (!item.IsFeature)
                    {
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="@item.ImageUrl" alt="Lights" style="width:100%" class="img-responsive" />
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="card col-md-6 col-sm-12 pl-3 border-0 pt-4">

            <h2 class="product-title"><strong>New @Model.Model @Model.YearOfMan Model</strong></h2>
            <p>Registered & verified</p>
            <p>@Model.Ratings<span class="fa fa-star text-warning"></span> (@Model.Ratings verified ratings) </p>
            <div class="rating">
                <span class="review-no"><h4>N @Model.Price / @Model.UnitOfPrice </h4></span>
                <h3 class="product-title">@Model.TypeOfCar </h3>
            </div>

            <div class="container ">
                <div class="row">


                    <div class="card col-lg-6 border-left-0 border-right-0 border-top-1 border-bottom-1 pt-3 pb-3">
                        <div class="mb-2"><img src="~/Images/lock.png"> <span>Quality Performance</span></div>
                        <div class="mb-2"><img src="~/Images/circle.png"> <span>Well functional AC control</span></div>
                        <div><img src="~/Images/check.png"> <span>Suberp quality</span></div>
                    </div>



                    <div class=" card col-lg-6 border-left-0 border-right-0 border-top-1 border-bottom-1 pt-3 pb-3">


                        <div class="mb-2"><img src="~/Images/chair.png"> <span>5 Seats</span></div>
                        <div class="mb-2"><img src="~/Images/depot.png"> <span>Fuel (Premium) </span></div>
                        <div><img src="~/Images/door.png"> <span>4 Doors</span></div>

                    </div>


                </div>
            </div>


            <form method="post" asp-controller="Car" asp-action="BookCarTrip">
                <div class="row mt-5">
                    <div class="card border-0 col-sm-12 col-md-12">
                        <div class="row">
                            <div class="form-group col-md-6 border-0 mb-5">
                                <h4 class="start">Pick Up Date</h4>
                                <input type='date' class="p-2" style="width:100%" name="pickupdate" id="pickupdate"/>
                            </div>
                            <div class="form-group col-md-6 border-0 mb-5">
                                <h4 class="start">Return Date</h4>
                                <input type='date' class="p-2" style="width:100%" name="returndate" id="returndate"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="card border-0 col-md-12 mt-3">
                        <h4 class="pick">Pick Up & Return Location</h4>
                        <div class="row">
                            <div class="form-group col-md-12 border-0 mb-5">
                                <select type="select" class="p-2" style="width:100%" name="location" id="trip-select">
                                    <option value="">Select location</option>
                                    @foreach (string name in Enum.GetNames(typeof(States)))
                                    {
                                        <option value="@name">@name</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    @if (Model.LastTrip.Status == "Done")
                    {
                        <div class="form-group col-md-12 border-0 mb-5">
                            <input type="submit" class="btn btn-color px-5 btn-send  pt-2 btn-block"
                                   value="Book this car" style="width:100%">
                        </div>

                    }
                    else
                    {
                        <blockquote class="text-danger">
                            <p>This Car is not Avaliable at this moment</p>
                            <p>Booked from @Model.LastTrip.PickUpDate.ToString("dd/M/yyyy") to @Model.LastTrip.ReturnDate.ToString("dd/M/yyyy")</p>
                        </blockquote>

                    }
                    <input type="hidden" name="carId" value="@Model.LastTrip.CarId" />
                    <input type="hidden" name="carName" value="@Model.Model @Model.YearOfMan Model" />
                    <input type="hidden" name="amount" id="amount" />
                    <input type="hidden" name="timeSpend" id="timeSpend" />
                    <input type="hidden" id="price" value="@Model.Price" />

                </div>
            </form>

        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="card col-md-12 col-sm-12  px-0 mb-3 shadow p-3 mb-5 bg-body rounded">
            <div class="card-header  border">Car details</div>
            <div class="card-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula enim rhoncus, vitae velit et habitant neque justo sed. Amet, in et tincidunt lectus laoreet.
                    Elementum quam dolor enim lacus, nunc nulla placerat egestas mauris. Diam semper vestibulum gravida enim orci varius. Suspendisse tellus in netus nulla erat ligula.
                    Tempus pellentesque habitant nec quis tempor erat id. Mi enim massa in diam viverra euismod. Lobortis ut varius imperdiet sit convallis vivamus nec ut ultrices
                    Quis eget vehicula in lobortis. Bibendum turpis cum tempor odio. Luctus sit arcu nec vitae arcu fermentum at venenatis. Massa massa amet vel maecenas a.
                    Odio cras odio sit lacinia adipiscing venenatis. Vitae, mauris nisl faucibus a sed sed. Id viverra sit ac molestie mattis nisl. Pharetra, ut in et senectus dapibus et elementum amet viverra.
                    In ultrices risus nunc, congue. Odio aliquet tempor, augue amet, mattis urna. Et pharetra habitasse accumsan, ac adipiscing magna.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula enim rhoncus, vitae velit et habitant neque justo sed. Amet, in et tincidunt lectus laoreet.
                    Elementum quam dolor enim lacus, nunc nulla placerat egestas mauris.Diam semper vestibulum gravida enim orci varius. Suspendisse tellus in netus nulla erat ligula.
                    Tempus pellentesque habitant nec quis tempor erat id. Mi enim massa in diam viverra euismod. Lobortis ut varius imperdiet sit convallis vivamus nec ut ultrices. Quis eget vehicula in lobortis.
                    Bibendum turpis cuio aliquet tempor, augue amet, mattis urna. Et pharetra habitasse accumsan, ac adipiscing magna.
                </p>
            </div>
        </div>
    </div>

    <div class="card-deck">
        <div class="row">
            <div class="card col-lg-6 px-0 mb-2 shadow p-3 mb-5 bg-body rounded">
                <div class="card-header">Features</div>
                <div class="card-body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula enim
                        rhoncus, vitae velit et habitant neque justo sed. Amet, in et tincidunt lectus
                        laoreet. Elementum quam dolor enim lacus, nunc nulla placerat egestas mauris.
                        Diam semper vestibulum gravida enim orci varius. Suspendisse tellus
                        in netus nulla erat ligula. Tempus pellentesque habitant nec quis tempor erat
                        id. Mi enim massa in diam viverra euismod. Lobortis ut varius imperdiet sit
                        convallis vivamus nec ut ultrices. Quis eget vehicula in lobortis. Bibendum
                        turpis cum tempor odio. Luctus sit arcu nec vitae arcu fermentum at
                        venenatis. Massa massa amet vel maecenas a. Odio cras odio sit lacinia
                        adipiscing venenatis. Vitae, mauris nisl faucibus a sed sed. Id viverra sit ac
                        molestie mattis nisl. Pharetra,
                    </p>
                </div>
            </div>

            <div class="card col-lg-6 px-0 mb-2 shadow p-3 mb-5 bg-body rounded">
                <div class="card-header">Specifications</div>
                <div class="card-body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula enim
                        rhoncus, vitae velit et habitant neque justo sed. Amet, in et tincidunt lectus
                        laoreet. Elementum quam dolor enim lacus, nunc nulla placerat egestas mauris.
                        Diam semper vestibulum gravida enim orci varius. Suspendisse tellus
                        in netus nulla erat ligula. Tempus pellentesque habitant nec quis tempor erat
                        id. Mi enim massa in diam viverra euismod. Lobortis ut varius imperdiet sit
                        convallis vivamus nec ut ultrices. Quis eget vehicula in lobortis. Bibendum
                        turpis cum tempor odio. Luctus sit arcu nec vitae arcu fermentum at
                        venenatis. Massa massa amet vel maecenas a. Odio cras odio sit lacinia
                        adipiscing venenatis. Vitae, mauris nisl faucibus a sed sed. Id viverra sit ac
                        molestie mattis nisl. Pharetra,
                    </p>
                </div>
            </div>
        </div>
    </div>



    <div class="row">

        <div class="card  col-md-12 col-sm-12  px-0 mt-2">
            <div class="card-header d-flex justify-content-between">
                <p>Customer Feedbacks</p>
                <a href="#" class="card-link ml-auto text-warning">See all</a>
            </div>



            <div class="card-body">
                <div class="card border-0 justify-content-start">
                    <div class="card-body d-flex justify-content-between p-1">


                        <h6 class="card-title text-left">
                            A very good car &nbsp;
                            <span class="fa fa-star stars text-warning"></span>
                            <span class="fa fa-star text-warning"></span>
                            <span class="fa fa-star text-warning"></span>
                            <span class="fa fa-star text-warning"></span>
                            <span class="fa fa-star text-warning"></span>
                        </h6>
                        <h6 class="card-title text-right">11/04/2022</h6>


                    </div>
                </div>


                <p class="mb-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula enim
                    rhoncus, vitae velit et habitant neque justo sed. Amet, in et tincidunt lectus
                    laoreet. Elementum quam dolor enim lacus, nunc nulla placerat egestas mauris.
                </p>


                <h6 class="aba">Abayomi Sunday</h6>
            </div>
        </div>
        <div class="card  col-md-12 col-sm-12  px-0 mb-3">
            <div class="card border-0">
                <div class="card-body d-flex justify-content-between p-3">

                    <h6 class="card-title">
                        Awesome car to drive &nbsp;
                        <span class="fa fa-star text-warning"></span>
                        <span class="fa fa-star text-warning"></span>
                        <span class="fa fa-star text-warning"></span>
                        <span class="fa fa-star text-warning "></span>
                        <span class="fa fa-star text-warning"></span>
                    </h6>
                    <h6 class="card-title text-right">11/04/2022</h6>

                </div>
                <p class="mb-3 p-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vehicula enim
                    rhoncus, vitae velit et habitant neque justo sed. Amet, in et tincidunt lectus
                    laoreet. Elementum quam dolor enim lacus, nunc nulla placerat egestas mauris.
                </p>
                <h6 class="p-3">Abayomi Sunday</h6>
            </div>

        </div>

    </div>

</div>

carRentals-MVC/CarRentalsApp-WEB/Views/Car/SearchCar.cshtml
@model IEnumerable<CarSearchResponseViewModel>
@{
    ViewData["Title"] = "CAR SEARCH";
}


<div class="list-img">
    <img src="~/images/list-banner.png" width="100%" />
</div>
<div class="car-list-container">
    <div class="container text-white text-center">
        <div class="list-text">
            <h2>Car Listing</h2>
            <p>Discover the best cars for you to run the day</p>
        </div>
    </div>

    <div class="container mt-2">
        <div class="row">
            <div class="col-md-6">
                <div class="mt-1">
                    <a href="#" class="text-dark"><i class="fas fa-arrow-left mr-2"></i>Go Back</a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="input-group has-search">
                    <span class="fa fa-search form-control-feedback"></span>
                    <input type="text"
                           class="form-control"
                           placeholder="Search for cars" />
                    <div class="input-group-append">
                        <button class="border border-none car-search-btn px-4 text-white"
                                type="button">
                            <span class="px-3">Search</span>
                            <!-- <i class="fa fa-search"></i> -->
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">


        @foreach (var item in Model)
        {
            <div class="col-md-4 mt-5 p-3 h-50 w-50">
                <div class="top-car-list border">
                    <a asp-action="Details">
                        <img src=@item.ImageUrl
                             alt=""
                             width="300"
                             height="250" />
                    </a>
                    <div class="car-list-text mt-4 px-3">
                        <a asp-action="#"><h2> @item.Model @item.YearOfMan</h2></a>
                        <div class="car-list-rate d-flex">
                            <p>@item.Rating</p>
                            <p><span class="fa fa-star checked mt-1"></span></p>
                            <p class="brackets">@item.NoOfPeople people hired so far</p>
                        </div>

                        <p>@item.Price/@item.UnitOfPrice</p>

                        @if (item.Avalability)
                        {
                            <a asp-action="Details" asp-route-id="@item.Id" class="text-danger font-weight-bolder view-details"> View Details<i class="fas fa-chevron-right pl-2 text-center"></i></a>
                        }

                        else
                        {
                            <blockquote class="blockquote text-danger">
                                <p class="mb-0"> Not Avalaible </p>
                            </blockquote>
                        }


                    </div>
                </div>

            </div>
        }


    </div>
    <nav aria-label="Page navigation" class="page-navigtion">
        <ul class="pagination">
            <li class="page-item d-flex align-items-center">
                <a href=""><i class="fa fa-chevron-left"></i></a>
                <a class="page-link ml-2" href="#">
                    Prev
                </a>
            </li>
            <li class="page-item ">
                <a class="page-link" href="#">
                    1
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">
                    2
                </a>
            </li>
            <li class="page-item d-flex align-items-center">

                <a class="page-link mr-2" href="#">
                    Next
                </a>
                <a href=""><i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </nav>

</div>
<section class="testimonials">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-12 col-sm-12">
                <div class="col-md-12 col-sm-12 text-center font-weight-bolder">
                    <h2>Testimonials</h2>
                    <p>What are people saying about us</p>

                </div>
                <div class="owl-carousel owl-theme" id="customer-testimonials">
                    <div class="item border">
                        <div class="shadow-effect">
                            <img class="img-circle" src="~/images/testimonial.png">
                            <div class="testimonial-name">
                                Paulson Aboyemi
                            </div>
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab accusamus atque in quasi,
                                tempore nam ullam aut tenetur reprehenderit animi repudiandae placeat sequi! Eos alias,
                                maxime exercitationem quo laudantium quos.
                            </p>
                            <div class="star-rates">
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>

                            </div>
                        </div>

                    </div>
                    <div class="item border">
                        <div class="shadow-effect">
                            <img class="img-circle" src="~/images/testimonial.png">
                            <div class="testimonial-name">
                                Paulson Aboyemi
                            </div>

                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab accusamus atque in quasi,
                                tempore nam ullam aut tenetur reprehenderit animi repudiandae placeat sequi! Eos alias,
                                maxime exercitationem quo laudantium quos.
                            </p>
                            <div class="star-rates">
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>

                            </div>

                        </div>

                    </div>
                    <div class="item border">
                        <div class="shadow-effect">
                            <img class="img-circle" src="~/images/testimonial.png">
                            <div class="testimonial-name">
                                Paulson Aboyemi
                            </div>
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab accusamus atque in quasi,
                                tempore nam ullam aut tenetur reprehenderit animi repudiandae placeat sequi! Eos alias,
                                maxime exercitationem quo laudantium quos.
                            </p>
                            <div class="star-rates">
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>

                            </div>
                        </div>

                    </div>

                    <div class="item">
                        <div class="shadow-effect">
                            <img class="img-circle" src="~/images/testimonial.png" width="100">
                            <div class="testimonial-name">
                                Paulson Aboyemi
                            </div>
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab accusamus atque in quasi,
                                tempore nam ullam aut tenetur reprehenderit animi repudiandae placeat sequi! Eos alias,
                                maxime exercitationem quo laudantium quos.
                            </p>
                            <div class="star-rates">
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>

                            </div>
                        </div>

                    </div>




                </div>
            </div>
        </div>
    </div>

</section>

carRentals-MVC/CarRentalsApp-WEB/Views/Car/Summary.cshtml
@model CarBookTripViewModel


@{   
    ViewData["Title"] = "Summary";
   
}


  <br><br><br><br><br>
                  <form method="post" asp-controller="Car" asp-action="Payment">
                      <div class="row pt-5 pb-5">
                          <div class="col-sm-3"></div>
                          <div class="card text-center pt-4 pb-2 px-4 col-sm-6 w-30">
                              <div class="card-body">
                                  <h1 class="card-title pb-5"><strong>Summary</strong></h1>
                                  <table class="table pb-5 mb-5 bg-white table-borderless w-100">

                                      <tr class="mb-3 summary-text">
                                          <th class="text-left">Name of Car</th>
                                          <td class="text-right">@Model.CarName</td>
                                      </tr>
                                      <tr>
                                          <th class="text-left">Pickup Date</th>
                                          <td class="text-right">@Model.Pickupdate</td>
                                      </tr>
                                      <tr>
                                          <th class="text-left">Return Date</th>
                                          <td class="text-right">@Model.Returndate</td>
                                      </tr>
                                      <tr>
                                          <th class="text-left">Number of Hours</th>
                                          <td class="text-right">@Model.TimeSpend Hours</td>
                                      </tr>
                                      <tr>
                                          <th class="text-left">Amount</th>
                                          <td class="text-right"><span style="text-decoration-line: line-through; text-decoration-style: double;">N</span> @Model.Amount</td>

                                      </tr>
                                      <tr>
                                          <th class="text-left">Pick up & return location</th>
                                          <td class="text-right">@Model.Location</td>
                                      </tr>
                                  </table>

                              </div>
                          </div>
                          <div class="col-sm-3"></div>
                      </div>

                      <div class="row pt-5 pb-5">
                          <div class="col-sm-3"></div>

                          <div class="card text-center pt-4 pb-2 px-4 col-sm-6 w-30">
                              <div class="card-body">
                                  <h1 class="card-title pb-5"><strong>Add payment method</strong></h1>

                                  <table class="table pb-5 mb-5 bg-white table-borderless w-100">

                                      <tr class="mb-3">
                                          <th class="text-center"><input class="form-check-input" type="radio" name="paymentMethod" value="Paystack" /></th>
                                          <td class="text-left"><label class="form-check-label" for="html">Paystack</label></td>
                                      </tr>
                                      <tr>
                                          <th class="text-center"><input class="form-check-input" type="radio" name="paymentMethod" value="Flutterwave" /></th>
                                          <td class="text-left"><label class="form-check-label" for="html">Flutterwave</label></td>
                                      </tr>
                                      <tr>
                                          <th class="text-center"><input class="form-check-input" type="radio" name="paymentMethod" value="CreditDebitCard" /> </th>
                                          <td class="text-left"><label class="form-check-label" for="html">Credit or Debit card</label></td>
                                      </tr>
                                      <tr>
                                          <th class="text-center"><input class="form-check-input" type="radio" name="paymentMethod" value="BankTransfer" /> </th>
                                          <td class="text-left"><label class="form-check-label" for="html">Bank Transfer</label></td>
                                      </tr>

                                  </table>

                                  <button type="submit" class="btn btn-color mb-3 w-100">Pay</button>

                              </div>
                          </div>
                          <div class="col-sm-3"></div>
                      </div>
                      <input type="hidden" name="tripId" value="@Model.TripId" />
                      <input type="hidden" value="@Model.Amount" name="amount" />
                      <input type="hidden" value="craftwordltd@gmail.com" name="email" />

                  </form>
     